products = [
    {
        '_id':1,
        "productname":'camera',
        'category':'electronics',
        'price':5000
    },
    {
        '_id':2,
        "productname":'mobile',
        'category':'electronics',
        'price':15000
    },
    {
        '_id':3,
        "productname":'laptop',
        'category':'electronics',
        'price':50000
    }
]