# Generated by Django 5.1.2 on 2024-10-11 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='values',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
